FROM centos/php-72-centos7

USER root

LABEL maintainer="zonlibi <phuongle@fincorp.vn>"

#RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#RUN yum update
#RUN cat /etc/yum.repos.d/CentOS-Base.repo
RUN ls /etc/yum.repos.d/
#RUN cat /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
RUN yum-config-manager --disable centos-sclo-rh
RUN yum-config-manager --disable centos-sclo-sclo
#RUN sed -i s/enabled=1/enabled=0/ /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
RUN sed -i s/#baseurl/baseurl/ /etc/yum.repos.d/CentOS-Base.repo
RUN sed -i s/mirrorlist.centos.org/vault.centos.org/ /etc/yum.repos.d/CentOS-Base.repo
RUN sed -i s/mirror.centos.org/vault.centos.org/ /etc/yum.repos.d/CentOS-Base.repo
RUN yum clean all
#RUN cat /etc/yum.repos.d/CentOS-Base.repo
RUN yum install -y epel-release
RUN yum install -y openvpn sed git openssl mysql
RUN ln -s /opt/rh/rh-php72/root/usr/bin/php /usr/bin/

WORKDIR /root
RUN git clone https://github.com/lhphuong86/OpenVPN-Admin
WORKDIR /root/OpenVPN-Admin
RUN cp -r "./installation/scripts" "/etc/openvpn/" && chmod +x "/etc/openvpn/scripts/"* && \
    cp "./installation/server.conf" "/etc/openvpn/" && mkdir "/etc/openvpn/ccd"


# change group nogroup to group nobody
RUN sed -i "s/group nogroup/group nobody/" "/etc/openvpn/server.conf" && \
    sed -i "s/explicit-exit-notify 1/explicit-exit-notify 0/" "/etc/openvpn/server.conf"

# Get the rsa keys
WORKDIR /root/
RUN curl -L "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/EasyRSA-unix-v3.0.6.tgz" -O && \
    tar -xaf "EasyRSA-unix-v3.0.6.tgz" && mv "EasyRSA-v3.0.6" /etc/openvpn/easy-rsa &&rm "EasyRSA-unix-v3.0.6.tgz"

COPY ./openvpn/docker-entrypoint.sh /usr/local/bin

# Make ip forwading and make it persistent
RUN echo "net.ipv4.ip_forward = 1" >> "/etc/sysctl.conf"

ENTRYPOINT ["docker-entrypoint.sh"]
